[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_swap = "CDnPGAFt6zbNXrYqkJW34BjAvqV2JJBY3UjiLWmQyd1R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "newdevnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
